
HTTP_ZEUS_AUTH_KEY = 'ZEUS_AUTH_KEY'
HTTP_X_ZEUS_ENVIRONMENT_ID = 'HTTP_X_ZEUS_ENVIRONMENT_ID'
HTTP_X_ZEUS_AUTH_KEY = 'HTTP_X_ZEUS_AUTH_KEY'
HTTP_X_ZEUS_SERVICE_PUBLIC_KEY = 'HTTP_X_ZEUS_SERVICE_PUBLIC_KEY'
HTTP_X_ZEUS_SERVICE_SECRET_KEY = 'HTTP_X_ZEUS_SERVICE_SECRET_KEY'

PERMISSION_ZEUS = "zeus"
PERMISSION_PUBLIC = "public"
PERMISSION_PRIVATE = "private"

ERROR_NOT_AUTHORIZED = "Not authorized"
ERROR_RECORD_NOT_FOUND = "Record not found"